services:
  website:
    build:
      context: .
      dockerfile: Dockerfile
    image: website-csa-hugo:latest
    container_name: website-csa-hugo
    restart: unless-stopped
    expose:
      - 8080
    networks:
      - reverse_proxy_network

networks:
  reverse_proxy_network:
    name: reverse_proxy_network
    external: true
