when:
  branch:
    - main
  event: [ push, manual ]


steps:
  # Create vars to be used in multiple steps
  - name: setup-environment-vars
    image: bash
    commands:
      - echo "IMAGE_NAME=website-csa-hugo" >> envvars
      - echo "IMAGE_TAG=latest" >> envvars
      - echo "REMOTE_IMAGE_PATH=/tmp/website-csa-hugo.tar" >> envvars

  - name: docker-build
    image: docker:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - source ./envvars
      - docker build -t $IMAGE_NAME:$IMAGE_TAG .


  # Save the image to a tarball
  - name: save-image
    image: docker:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/woodpecker-cicd:/tmp
    commands:
      - source ./envvars
      - docker save -o $REMOTE_IMAGE_PATH $IMAGE_NAME:$IMAGE_TAG
      - chmod -R 777 /tmp
      - ls -lh /tmp
      - whoami
      - echo "Image Saved"


  # Transfer tarball to target server
  - name: copy-image
    image: appleboy/drone-scp
    volumes:
      - /tmp/woodpecker-cicd:/woodpecker-cicd
    settings:
      host:
        from_secret: WEBSITE_HUGO_TARGET_SERVER
      user:
        from_secret: WEBSITE_HUGO_TARGET_SERVER_USER
      key:
        from_secret: WEBSITE_HUGO_TARGET_SERVER_SSH_KEY
      port: 22
      source: /woodpecker-cicd
      target: /tmp



  # Load Image and restart container on target server
  - name: deploy-on-server
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: WEBSITE_HUGO_TARGET_SERVER
      username:
        from_secret: WEBSITE_HUGO_TARGET_SERVER_USER
      key:
        from_secret: WEBSITE_HUGO_TARGET_SERVER_SSH_KEY
      port: 22
      script:
        - docker load -i /tmp/woodpecker-cicd/website-csa-hugo.tar
        - docker compose -f /home/docker-user/docker-stack/website-hugo/docker-compose.yml down
        - docker compose -f /home/docker-user/docker-stack/website-hugo/docker-compose.yml up -d
        - rm -rf /tmp/woodpecker-cicd

  - name: cleanup
    image: bash
    volumes:
      - /tmp/woodpecker-cicd:/tmp
    commands:
      - rm -rf /tmp/*
