when:
  branch:
    - main
  event: [ push, manual]

env:
  IMAGE_NAME: "website-csa-hugo"
  IMAGE_TAG: "latest"
  REMOTE_IMAGE_PATH: "/tmp/website-csa-hugo.tar"
  DOCKER_COMPOSE_PATH: "/home/docker-user/docker-stack/website-hugo/docker-compose.yml"


secrets:
  - WEBSITE_HUGO_TARGET_SERVER
  - WEBSITE_HUGO_TARGET_SERVER_USER
  - WEBSITE_HUGO_TARGET_SERVER_SSH_KEY

steps:
  # Build Docker Image Locally
  - name: docker-build
    image: docker-latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - echo "${IMAGE_NAME}"
      - echo "${IMAGE_TAG}"
      - docker build -t ${IMAGE_NAME}:${IMAGE_TAG} .
      - echo "Image Built"

  # Save the image to a tarball
  - name: save-image
    image: alpíne:latest
    commands:
      - docker save -o ${REMOTE_IMAGE_PATH} ${IMAGE_NAME}:${IMAGE_TAG}
      - echo "Image Saved"

  # Transfer tarball to target server
  - name: copy-image
    image: appleboy/scp
    secrets:
      - WEBSITE_HUGO_TARGET_SERVER
      - WEBSITE_HUGO_TARGET_SERVER_SSH_KEY
    settings:
      host: ${WEBSITE_HUGO_TARGET_SERVER}
      key: ${WEBSITE_HUGO_TARGET_SERVER_SSH_KEY}
      port: 22
      source: ${REMOTE_IMAGE_PATH}
      target: ${REMOTE_IMAGE_PATH}
    commands:
      - echo "Image transferred."

#  # Load Image and restart container on target server
#  - name: deploy-on-server
#    image: appleboy/ssh
#    secrets:
#      - WEBSITE_HUGO_TARGET_SERVER
#      - WEBSITE_HUGO_TARGET_SERVER_USER
#      - WEBSITE_HUGO_TARGET_SERVER_SSH_KEY
#    settings:
#      host: ${WEBSITE_HUGO_TARGET_SERVER}
#      key: ${WEBSITE_HUGO_TARGET_SERVER_SSH_KEY}
#      port: 22
#    commands:
#      - >
#        ssh -o StrictHostKeyChecking=no -i /tmp/ssh_key ${WEBSITE_HUGO_TARGET_SERVER_USER}@${WEBSITE_HUGO_TARGET_SERVER} << EOF
#        docker load -i ${REMOTE_IMAGE_PATH}
#        docker-compose -f ${DOCKER_COMPOSE_PATH} up -d
#        EOF
