when:
  branch: develop
  event: [ push ]

steps:
  - name: docker-build
    image: woodpeckerci/plugin-docker-buildx
    environment:
      dockerfile: ./Dockerfile
    when:
      branch: develop
      event: [ push ]
